name: Build and Deploy All Microservices

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        docker build -t auth-service ./auth-service
        docker build -t user-service ./user-service
        docker build -t product-service ./product-service

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./auth-service/auth-deployment.yaml
        kubectl apply -f ./auth-service/auth-service.yaml

        kubectl apply -f ./user-service/user-deployment.yaml
        kubectl apply -f ./user-service/user-service.yaml

        kubectl apply -f ./product-service/product-deployment.yaml
        kubectl apply -f ./product-service/product-service.yaml
